name: Lint

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Super-linter
        uses: super-linter/super-linter@v2.1.0
 
